# Generated by Django 4.2.2 on 2023-07-10 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listing',
            name='start_bid',
        ),
    ]
