# Generated by Django 4.2.2 on 2023-07-10 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_auction_listing_start_bid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction_listing',
            options={'ordering': ('-end_time',)},
        ),
    ]
